### ISSUE TITLE
[Feat]: String Case Converter

### ISSUE THREAD

**Issue by AbdulHameedi** [GitHub-Campus-Experts-Unilag/DevzenFrontend#11]
To work on the String Case Converter, Can I be assigned

**Comment by shegz101** [comment]
Please @AbdulHameedi are you making progress on this?

**Comment by AbdulHameedi** [comment]
@shegz101 , Yes I am.
I am sorry for the inactiveness. National grid and some others.

I will send PR ASAP

**Comment by AbdulHameedi** [comment]
UI and Functionalities Already Completed
