### ISSUE TITLE
[Feat]: Markdown Formatter

### ISSUE THREAD

**Issue by tdadadavid** [GitHub-Campus-Experts-Unilag/DevzenFrontend#18]
Build all the features of the Markdown formater page.

**Comment by adedamola-toye** [comment]
Can i be assigned this issue

**Comment by tdadadavid** [comment]
Assigned
Thanks for contributing.

**Comment by tdadadavid** [comment]
@adedamola-toye , please, are you actively working on this ?

**Comment by adedamola-toye** [comment]
Yes I am . It will be completed today
