### ISSUE TITLE
[Feat]: File format converter

### ISSUE THREAD

**Issue by tdadadavid** [GitHub-Campus-Experts-Unilag/DevzenFrontend#20]
Implement feature to convert different file formats for example
- CSV to JSON
- JSON to YAML
- YAML to CSV
- JSON to CSV
- CSV to TSV
and many more.

**Comment by PetJs** [comment]
@shegz101 Can i be assigned this issue?

**Comment by tdadadavid** [comment]
Assigned.
Thanks for contributing!

**Comment by tdadadavid** [comment]
@PetJs, please are you actively working on this

**Comment by PetJs** [comment]
It has been merged
@tdadadavid
