### ISSUE TITLE
Create the Auth UI

### ISSUE THREAD

**Issue by shegz101** [GitHub-Campus-Experts-Unilag/DevzenFrontend#4]
For this project, we will be using the Google and Github auth methods. Please feel free to help use create the UI for this.

**Comment by PetJs** [comment]
can i be assigned this issue

**Comment by NureniJamiu** [comment]
Hi @shegz101, I can see no one is assigned this issue yet, I'd like to work on it if still available please.

**Comment by shegz101** [comment]
There was a mix up. I am closing this issue. I assigned it already as the landing page.
