### ISSUE TITLE
Build out the Landing Page

### ISSUE THREAD

**Issue by shegz101** [GitHub-Campus-Experts-Unilag/DevzenFrontend#5]
You can head to the Build design on Figma and spot the Hero Section (Landing Page) design. We need a Contributor to help us build a pixel-perfect landing page UI for this project.

**Comment by ayobami11** [comment]
@shegz101 Can I be assigned this issue?

**Comment by shegz101** [comment]
> @shegz101 Can I be assigned this issue?

Sure.
